// <auto-generated />
namespace DV.FrenteLoja.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbFirstDellaVia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbFirstDellaVia));
        
        string IMigrationMetadata.Id
        {
            get { return "201801111301536_dbFirstDellaVia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
