// <auto-generated />
namespace DV.FrenteLoja.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class criacao_tabela_grupo_e_subgrupo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criacao_tabela_grupo_e_subgrupo));
        
        string IMigrationMetadata.Id
        {
            get { return "201908291833094_criacao_tabela_grupo_e_subgrupo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
