// <auto-generated />
namespace DV.FrenteLoja.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ajustes_DB27 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajustes_DB27));
        
        string IMigrationMetadata.Id
        {
            get { return "201912140047538_ajustes_DB27"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
